# Generated by Django 5.0.6 on 2024-09-01 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_age_alter_user_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_type', models.CharField(max_length=200)),
                ('aim_count', models.IntegerField()),
                ('done_count', models.IntegerField()),
                ('done_at', models.DateTimeField()),
                ('user_nickname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
